import React from "react";
import Head from "next/head";
import { useEffect } from "react";
import Download from "../../components/Downolad";
export default function Post({ post }) {
  const materials = post.attributes.materials.data;
  useEffect(function () {
    const postContent = document.querySelector(".post-content");
    postContent.innerHTML = post.attributes.content.replaceAll(
      "/uploads",
      "https://annachatterbox.herokuapp.com/uploads"
    );
    // .replaceAll("<p>&nbsp;</p>", "");
  }, []);
  return (
    <>
      <Head>
        <title>{post.attributes.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 className="heading-post">
          <span>{post.attributes.title}</span>
        </h2>
        <section className="post-content"></section>
        {materials ? (
          <section className="materials">
            <h2 className="heading-materials">Materiały</h2>
            <hr></hr>
            <div className="materials__links">
              {materials.map((m) => {
                return (
                  <Download
                    key={m.id}
                    url={m.attributes.url}
                    filename={m.attributes.name}
                    link={m.attributes.alternativeText}
                  ></Download>
                );
              })}
            </div>
          </section>
        ) : (
          <>
            <p>&nbsp;</p>
            <hr></hr>
          </>
        )}
      </main>
    </>
  );
}

export async function getStaticPaths() {
  const res = await fetch(
    `${
      process.env.DEVELOPMENT_BACKEND_HOST
        ? process.env.DEVELOPMENT_BACKEND_HOST
        : process.env.PRODUCTION_BACKEND_HOST
    }/api/articles?populate[0]=category`
  );
  const strapi = await res.json();

  const paths = strapi.data.map((p) => {
    return {
      params: {
        catId: `${p.attributes.category.data.attributes.name}`,
        postId: `${p.attributes.slug}`,
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps(context) {
  const { params } = context;
  const res = await fetch(
    `${
      process.env.DEVELOPMENT_BACKEND_HOST
        ? process.env.DEVELOPMENT_BACKEND_HOST
        : process.env.PRODUCTION_BACKEND_HOST
    }/api/articles?filters[slug][$eq]=${params.postId}&populate=*`
  );
  const strapi = await res.json();
  const res2 = await fetch(
    `${
      process.env.DEVELOPMENT_BACKEND_HOST
        ? process.env.DEVELOPMENT_BACKEND_HOST
        : process.env.PRODUCTION_BACKEND_HOST
    }/api/categories/`
  );
  const strapi2 = await res2.json();
  return {
    props: {
      post: strapi.data[0],
      categories: strapi2.data,
    },
    revalidate: 60,
  };
}
