import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import fetchData from "../../functions/fetchData";
export default function Category({ posts }) {
  return (
    <>
      <Head>
        <title>
          {posts[0]
            ? posts[0].attributes.category.data.attributes.name
            : "Brak wpisów"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="heading-category">
        <span>
          {posts[0]
            ? posts[0].attributes.category.data.attributes.name
            : "Brak wpisów"}
        </span>
      </h2>
      <main>
        {posts
          ? posts.map((p) => {
              return (
                <div className="post-intro" key={p.id}>
                  <div className="post-intro__header">
                    <div className="post-intro__title">
                      <Link
                        href={`/${p.attributes.category.data.attributes.slug}/${p.attributes.slug}`}
                      >
                        <a>
                          <h2>
                            {p.attributes.title}
                            <span
                              className={`post-intro__level-button post-intro__level-button--${
                                p.attributes.level.data !== null
                                  ? p.attributes.level.data.attributes.value
                                  : "none"
                              }`}
                            ></span>
                          </h2>
                        </a>
                      </Link>
                    </div>
                    <div className="post-intro__date">
                      <span>{p.attributes.commit}</span>
                    </div>
                  </div>
                  <div className="post-intro__dsc">
                    {" "}
                    <div className="image post-intro__img">
                      {" "}
                      <Image
                        src={p.attributes.cover.data.attributes.url}
                        width="200px"
                        height="200px"
                        quality={100}
                      ></Image>
                    </div>
                    <div className="post-intro__paragraph">
                      {" "}
                      <p>{p.attributes.description}</p>
                      <Link
                        href={`/${p.attributes.category.data.attributes.slug}/${p.attributes.slug}`}
                      >
                        <a className="standard-btn">
                          <span>Czytaj dalej</span>
                        </a>
                      </Link>
                    </div>
                  </div>
                  <hr></hr>
                </div>
              );
            })
          : " "}
      </main>
    </>
  );
}

export async function getStaticPaths() {
  const res = await fetchData(`/api/categories/`);
  const strapi = await res.json();
  const paths = strapi.data.map((c) => {
    return {
      params: {
        catId: `${c.attributes.slug}`,
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps(context) {
  const { params } = context;
  const res1 = await fetchData(
    `/api/articles?filters[category][slug][$eq]=${params.catId}&populate=*&sort[0]=commit:desc`
  );
  const strapi1 = await res1.json();
  const res2 = await fetchData(`/api/categories/`);
  const strapi2 = await res2.json();
  return {
    props: {
      posts: strapi1.data,
      categories: strapi2.data,
    },
    revalidate: 10,
  };
}
