import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
export default function Home({ posts, categories }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">My Blog!</a>
        </h1>
        <h2 className={styles.title}>Look at our topics</h2>
        {categories.map((c) => {
          return (
            <Link key={c.id} href={`/${c.attributes.name}`}>
              <a>
                <h2>{c.attributes.name}</h2>
              </a>
            </Link>
          );
        })}
        <h2 className={styles.title}>Look at lasts posts...</h2>
        {posts.map((p) => {
          return (
            <Link
              key={p.id}
              href={`/${p.attributes.category.data.attributes.name}/${p.attributes.slug}`}
            >
              <a>
                <div>
                  <h2>
                    {p.attributes.category.data.attributes.name} -
                    {p.attributes.title}
                  </h2>
                  <p>{p.attributes.description}</p>
                </div>
                <hr></hr>
              </a>
            </Link>
          );
        })}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps() {
  const res1 = await fetch(
    " http://localhost:1337/api/articles?sort[0]=publishedAt:desc&pagination[page]=1&pagination[pageSize]=5&populate[0]=category"
  );
  const res2 = await fetch(" http://localhost:1337/api/categories/");
  const strapi1 = await res1.json();
  const strapi2 = await res2.json();
  return {
    props: {
      posts: strapi1.data,
      categories: strapi2.data,
    },
    revalidate: 60,
  };
}
